# Generated by Django 3.1.7 on 2021-04-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
